### PR TITLE
Fix file structure in base's css and add some minor css to base

### PR DESCRIPTION
**Pull request by astyrmoe**
Including fix variables

### CODE REVIEW

**Comment by kalkins** [comment]
Mostly good, but it seems to break some stuff on the login page.

screenshot_20181228_205439

**Comment by astyrmoe** [comment]
I have now fixed and updated the log in page with the new design. @kalkins

**Review by kalkins — APPROVED** [review]
I think the highlighting on the login inputs are a bit much, but I'll approve it. You can merge when you want

**Comment by kalkins** [comment]
I've merged in the dev branch, so it can be merged

**Comment by astyrmoe** [comment]
I was a bit uncertain about that highlighting in the login input, but that is just a small design choice that I can fix later.

**Pull request merged**
